### ISSUE TITLE
Policy Build not working

### ISSUE THREAD

**Issue by ptc-bsorek** [azure-ad-b2c/vscode-extension#1]
Maybe I am doing something wrong, but when I try the policy build no policies are generated. The only thing that gets generated are the directories, but they are all empty.

**Comment by Mohammed-El-Nabulsi** [comment]
You must make sure that the policy files are within your project root directory - it's a little bit annoying to be honest as you must get rid of a nested project structure if you want to use this feature.

We are currently trying to find a way to get around this though... but it seems to require a pull request unfortunately :/
