### ISSUE TITLE
Refactor Build Policy functionality

### ISSUE THREAD

**Issue by cwoolum** [azure-ad-b2c/vscode-extension#11]
I'd like the be able to use the build policy functionality as part of a custom Azure Pipelines task that could build the policy during a build.

Would you accept a PR that refactors that module and exports it so it can be imported and used by other NPM libraries?

**Comment by yoelhor** [comment]
Please see this [article](https://docs.microsoft.com/en-us/azure/active-directory-b2c/deploy-custom-policies-devops).
