### ISSUE TITLE
Upload Policy Feature App Registration requires Legacy App Registration which is no longer available

### ISSUE THREAD

**Issue by wiemerr** [azure-ad-b2c/vscode-extension#16]
Is there a way to register the application for the upload policy feature using the new App Registration experience?  My tenant no longer allows the legacy experience.

**Comment by AtToftegaard** [comment]
It'll work with a registration made under  'App registrations (Preview)' in your B2C-resource. 
BUT remember to enable 'treat as public client' under 'advanced settings' on the app-registration.

**Comment by yoelhor** [comment]
Thanks for your feedback I updated the doc https://github.com/azure-ad-b2c/vscode-extension/blob/master/src/help/policy-upload.md
