### ISSUE TITLE
Turn B2C Policy Build into a Github and Pipelines task

### ISSUE THREAD

**Issue by piquet-h** [azure-ad-b2c/vscode-extension#19]

**Comment by Norrch2** [comment]
Hi @piquet-h I have created a similar powershell script that performs this that can easily be added to a b2c pipeline. 

```powershell
#ReadApplicationSettings
$Environment = $env:ENVIRONMENT

$applicationSettings = Get-Content "appsettings.json" | ConvertFrom-Json
$environmentSettings = $applicationSettings.Environments.where({$_.Name -eq $Environment})

#replace Settings:Tenant
$policycontent = $policycontent -replace "{Settings:Tenant}", $environmentSettings.Tenant

foreach ($setting in $environmentSettings.PolicySettings.PsObject.Properties)
{
    $policycontent = $policycontent -replace "{Settings:$($setting.Name)}", $setting.value
}
```

I have appended this to [powershell script](https://docs.microsoft.com/en-us/azure/active-directory-b2c/deploy-custom-policies-devops#configure-an-azure-repo) already on Microsoft documentation right after line 22 $policycontent = Get-Content $PathToFile.

The only variable that you need to set in the pipeline is Environment and that is equal to which environment you want to publish. 

Hope this helps.
