### ISSUE TITLE
Policy upload always asks to login and does not upload policy

### ISSUE THREAD

**Issue by guestdj** [azure-ad-b2c/vscode-extension#20]
I've followed the steps in your article that linked to the instructions in configuring the VSCode to upload a custom policy doc, by configuring Graph API with B2C (https://github.com/azure-ad-b2c/vscode-extension/blob/master/src/help/policy-upload.md)

When i do a SHIFT + CTRL + U in VS code I get a login prompt, I copy the code into the web page, login and get the message "You have signed in to the Graph API application on your device. You may now close this window."

When do SHIFT + CTRL + U again I get the same login prompt in VS Code!?

When setting the Reply URL for the Graph Api in B2C I set it to https://[MyB2CTenant].b2clogin.com/oauth2/nativeclient

Is this a bug, what should happen from VSCode once I have logged in?

Using VSCode 1.45.1 on WIndows 10

**Comment by hhao01-becls** [comment]
I think I know the reason. You must enable 'treat application as public client' under 'Supported account types' in the menu 'Authentication'.

**Comment by saggiyogesh** [comment]
Yeah, Thanks.
It's working.

**Comment by LockTar** [comment]
Thanks @hhao01-becls! I had the same problem. No notification at all. I only got a strange notification when I tried to upload all policies. It was something like "couldn't get accesstoken from undefined". 

Changed the setting to public client "Yes" and it is working correctly!

**Comment by yoelhor** [comment]
Close due to #34 fix
