### ISSUE TITLE
App InSight Date Issue

### ISSUE THREAD

**Issue by rprohit66** [azure-ad-b2c/vscode-extension#24]
I have enabled the App Insight and getting the logs. I observed that there is difference in DateTime Showing in the B2C Trace and App InSight Explorer. Below are the screenshots. 

**B2C Trace App Insight**

![image](https://user-images.githubusercontent.com/41752010/89808215-703e7300-db57-11ea-9974-c288513cb525.png)

**App InSight Explorer**

![image](https://user-images.githubusercontent.com/41752010/89808334-9ebc4e00-db57-11ea-97c4-608cb11d58d4.png)

Is this how the system has been design or there is any issue?

**Comment by wiemerr** [comment]
I see the same problem.  It also appears that the sort order of app insights entries is wrong because it rounds or truncates to seconds so that when there are many entries in the same second the order is often wrong.

**Comment by yoelhor** [comment]
Thanks for the feedback. This issue will be solved in the next version.
