### ISSUE TITLE
[Feature Request] Support building policies not in root folder

### ISSUE THREAD

**Issue by RossBarnie** [azure-ad-b2c/vscode-extension#25]
I have some experimental custom policies that I want to manage within the same project but with separate implementations. To enable this, I'd like the extension's "Build policies" task to support folders other than the root folder so that it will work if I have the following file structure:
```
- Experiment1
  - TrustFrameworkBase.xml
  - TrustFrameworkExtensions.xml
  - appsettings.json
- Experiment2
  - TrustFrameworkBase.xml
  - appsettings.json
```

This also matches the AD B2C sample implementations repo https://github.com/azure-ad-b2c/samples/tree/master/policies

**Comment by BradCandell** [comment]
I think this will be implemented if we can get the Pull Request that @Norrch2 has pending.

#30

I'd love for that to get implemented as well, but I'm wondering if anyone is keeping up on this repo anymore?

**Comment by yoelhor** [comment]
Thank for the contribution. The #30 PR is now merged and a new version will be published later today.
