### ISSUE TITLE
The Graph API ClientId has not been set in Settings

### ISSUE THREAD

**Issue by leniel** [azure-ad-b2c/vscode-extension#3]
How to overcome this error when trying to upload the policy files to Azure?

<img width="1440" alt="Screen Shot 2019-07-08 at 15 17 23" src="https://user-images.githubusercontent.com/764854/60832977-a1e64d00-a193-11e9-9ea0-47b7483cc2fb.png">

**Comment by kevinreck** [comment]
It looks like either the settings is writing the value incorrectly, or the code is reading it wrong:

Settings creates:
`"aadb2c.graph.clientid": "<Your App Id>"`


but the extension expects the settings to be like this
```
"aadb2c.graph": {
	"clientid": "<Your App Id>"
}
```

Here's a link to the code that reads the value
https://github.com/azure-ad-b2c/vscode-extension/blob/master/src/B2CUtils.ts#L126

**Comment by leniel** [comment]
I managed to upload the policy using this new method:

https://github.com/azure-ad-b2c/vscode-extension/blob/master/src/help/policy-upload.md

**Comment by mleziva** [comment]
I am experiencing this issue even with the ClientId being set correctly.

Repro steps:

1. Follow tutorial: https://github.com/azure-ad-b2c/vscode-extension/blob/master/src/help/policy-upload.md
2. It is working correctly
3. Restart computer and try upload. Prompted to enter code again to confirm app registration. Close browser instead of entering code
4. Attempt to upload policies and see client ID error below and no option to enter code

Settings:
![image](https://user-images.githubusercontent.com/6925381/65269918-bcb43680-dadf-11e9-9cba-c4cfd3999e82.png)

Error:
![image](https://user-images.githubusercontent.com/6925381/65269949-c63d9e80-dadf-11e9-9725-0263ff1a94ec.png)

**Comment by nevseev** [comment]
There’s a pull request pending, which fixes the issue. Nothing to do with the client Id. Assignment operator was used instead of the equality one in an if statement.

**Comment by mleziva** [comment]
Thanks, that will make the error actual apparent. Turns out my issue was that the Tenant needed to be set correctly in the appsettings.json file and now it is working for me

**Comment by nevseev** [comment]
@mleziva glad to be of use 🙂

**Comment by Tanzy** [comment]
> Thanks, that will make the error actual apparent. Turns out my issue was that the Tenant needed to be set correctly in the appsettings.json file and now it is working for me

How did you do it? I keep getting tenant needs to be DNS or something like that

**Comment by bruceharrison1984** [comment]
I just ran into this issue. My problem was I had added my Tenant as the `Developement` tenant, but left the default values for the other tenants:

```js
{
    "PoliciesFolder": "c:\\Users\\xxx\\Development\\xxx\\b2c",
    "EnvironmentsFolder": "Environments",
    "Environments": [
        {
            "Name": "Development",
            "Production": false,
            "Tenant": "MY_DEV_TENANT.onmicrosoft.com",
            "PolicySettings": {
                "IdentityExperienceFrameworkAppId": "Your dev environment AD app Id",
                "ProxyIdentityExperienceFrameworkAppId": "Your dev environment AD Proxy app Id",
                "FacebookAppId": "0"
            }
        },
        {
            "Name": "Test",
            "Production": false,
            "Tenant": "your-test-tenant.onmicrosoft.com",
            "PolicySettings": {
                "IdentityExperienceFrameworkAppId": "Your test environment AD app Id",
                "ProxyIdentityExperienceFrameworkAppId": "Your AD test environment Proxy app Id",
                "FacebookAppId": "0"
            }
        },
        {
            "Name": "QA",
            "Production": false,
            "Tenant": "your-qa-tenant.onmicrosoft.com",
            "PolicySettings": {
                "IdentityExperienceFrameworkAppId": "Your QA environment AD app Id",
                "ProxyIdentityExperienceFrameworkAppId": "Your QA environment AD Proxy app Id",
                "FacebookAppId": "0"
            }
        },
        {
            "Name": "Production",
            "Production": true,
            "Tenant": "your-production-tenant.onmicrosoft.com",
            "PolicySettings": {
                "IdentityExperienceFrameworkAppId": "Your QA environment AD app Id",
                "ProxyIdentityExperienceFrameworkAppId": "Your production environment AD Proxy app Id",
                "FacebookAppId": "0"
            }
        }
    ]
}
```

removing all tenants except for the one that actually exists and re-running the `get id` command fixes the issue:

```js
{
    "PoliciesFolder": "c:\\Users\\xxx\\Development\\xxx\\b2c",
    "EnvironmentsFolder": "Environments",
    "Environments": [
        {
            "Name": "Development",
            "Production": false,
            "Tenant": "MY_DEV_TENANT.onmicrosoft.com",
            "PolicySettings": {
                "IdentityExperienceFrameworkAppId": "<guid>",
                "ProxyIdentityExperienceFrameworkAppId": "<guid>",
                "AADExtensionsAppId": "<guid>",
                "AADExtensionsObjectId": "<guid>"
            }
        }
    ]
}
```
