### ISSUE TITLE
[Feature Request] - Building Policies allows for a {Setting:Filename} token that uses the actual (XML) filename

### ISSUE THREAD

**Issue by BradCandell** [azure-ad-b2c/vscode-extension#31]
Allow a special `{Setting:Filename}` token to be used within the `B2C Build Policy` command that will be replaced with the name of the file on disk. 

Notes:
- Would truncate the file extension (`.XML`)
- Would truncate `B2C_1[A]_` if a developer included that in the filename
- Would replace unsupported characters with underscore (_)
- Would ignore a `Filename` value in the `appsettings.json`

Examples:

Filename | Value of {Setting:Filename}
---------- | --------------------------------------
TrustFrameworkBase.xml | TrustFrameworkBase
TrustFramework.Base.xml | TrustFramework_Base
PasswordReset.xml | PasswordReset
B2C_PasswordReset.xml | PasswordReset
B2C_1A_PasswordReset.xml | PasswordReset
B2C_1_PasswordReset.xml | PasswordReset
Password.Reset.xml | Password_Reset
Password_Reset.xml | Password_Reset

Note - I am not 100% sold on the removal of B2C_1[A], because a developer can add or remove that in his/her Policy files where they will use.

# Overall Value
In most cases, I am finding that I am creating a file that is the same as the Policy Name/ID. I could simplify my policy header if the `{Setting:Filename}` token could just match the name of the file in my repository.

**Comment by yoelhor** [comment]
Thanks for the feedback, good point. I'm adding this feature to the new version which will be published today
