### ISSUE TITLE
Cannot Login 

### ISSUE THREAD

**Issue by cgat** [azure-ad-b2c/vscode-extension#32]
I've followed the instructions [here](https://github.com/azure-ad-b2c/vscode-extension/blob/master/src/help/policy-upload.md), however, when I attempt to sign in to azure, I get the following error:

`AADSTS500113: No reply address is registered for the application.`

To be clear, I am doing the following after I have registered the graph API permitted application on Azure:

1. Run the vscode command palette with "B2C Upload Policy"
2. I get prompted to login, click login.
3. Enter code
4. Login with my credentials
5. See the error screen

Do I need setup a redirect link or something in the application auth settings: 
![image](https://user-images.githubusercontent.com/3103805/100777438-1a435300-3406-11eb-9eee-f8039ada2ba2.png)

Thanks

**Comment by BradCandell** [comment]
Yes, you are correct, you will need some sort of Redirect Uri.

I used `myapp://auth`

I will walk-thru those steps again and make sure nothings changed to make sure that it all works.

**Comment by BradCandell** [comment]
Make sure that you're creating the Redirect Uri for the "Mobile and desktop applications".

If you're still having troubles, I will happily document the step-by-step that I followed to get it working.

**Comment by cgat** [comment]
Thanks for the help @BradCandell . That worked, allowing me to complete the login. Should I stay logged in after this, or is the expectation that I log in on each upload? Currently, I have to continue to log in and the files don't appear to upload. I can open a separate ticket or go to stackoverflow if you like, as this isn't related to the original question.

**Comment by BradCandell** [comment]
In your application registration, make sure that you also `Allow public client flows` to also support the desktop flow.

**Comment by cgat** [comment]
@BradCandell Thanks. That worked. This makes my life a lot easier.

**Comment by BradCandell** [comment]
@cgat - Glad to hear! I too have found the VSCode extension to drastically improve the development experience of B2C's Custom Policies / Trust Framework.

**Comment by Norrch2** [comment]
@cgat I noticed that this issue is still open. Can you close it if you have a resolution :D
