### ISSUE TITLE
Application Insights produced empty results

### ISSUE THREAD

**Issue by markharrison** [azure-ad-b2c/vscode-extension#35]
I'm not getting any Trace info in VSCode - get error "Application Insights produced empty results"

I can see the Trace information is being logged in App Insights ... it just not getting to the VSCode panel

**Comment by yoelhor** [comment]
Could you check the duration settings 

![image](https://user-images.githubusercontent.com/20111866/107918885-2786cd00-6f73-11eb-8af0-d1bf7b442229.png)

**Comment by markharrison** [comment]
I've tried 2,20,200,2000,20000 in that field ... same response. 

![image](https://user-images.githubusercontent.com/5177824/107933894-412a1380-6f77-11eb-8867-43312da62dd2.png)

**Comment by yoelhor** [comment]
Could you run the following GET request

```
GET https://api.applicationinsights.io/v1/apps/<App-ID>/events/traces?timespan=PT12H&$filter=startswith(customDimensions/EventName, 'Journey Recorder')&$top=30&$orderby=timestamp desc&$select=id,timestamp,trace/message,customDimensions

X-API-Key: <App-secret>
```

**Comment by markharrison** [comment]
Am I formatting the Payload correct 

![image](https://user-images.githubusercontent.com/5177824/107942182-ce269a00-6f82-11eb-8b5a-75710a79b9ef.png)

**Comment by markharrison** [comment]
I now have this working.  If you create an App Insights using the Workspace-based version it doesnt work .   if you use Classic - it does work 👍

![image](https://user-images.githubusercontent.com/5177824/107990886-5b8edc00-6fcd-11eb-8066-006cce293570.png)

**Comment by ff-gustavorocha** [comment]
> I now have this working. If you create an App Insights using the Workspace-based version it doesnt work . if you use Classic - it does work 👍
> 
> ![image](https://user-images.githubusercontent.com/5177824/107990886-5b8edc00-6fcd-11eb-8066-006cce293570.png)

I don't how how you figure it out by yourself. well done.

classic AI seems to have a lifetime now. It will be retired in Feb2024. 
Is there any plan to support workspace based AI on this extension?

Thanks
