### ISSUE TITLE
Wrong folders used during PolicyBuild

### ISSUE THREAD

**Issue by ericbeaudry** [azure-ad-b2c/vscode-extension#44]
There are a couple issues lurking behind the scenes in this part of the code when you change the defaults in the appsettings.json file and expect the Policies to be built from "PoliciesFolder" into the "EnvironmentsFolder"

![image](https://user-images.githubusercontent.com/30331106/111311449-a172aa80-8634-11eb-81e9-29ebe1fd7b2a.png)

I believe the provided PoliciesFolder setting should be used to scan for policies. If it's null scan from the root only instead.

Later when creating the environmentsRootPath variable you join with the hardcoded value "Environments" instead of using the provided EnvironmentsFolder setting.

**Comment by yoelhor** [comment]
Hi @Norrch2, 

I would be grateful if you could check this issue. It may related to the [PR #30 ](https://github.com/azure-ad-b2c/vscode-extension/pull/30).

Yoel

**Comment by Norrch2** [comment]
@ericbeaudry 

I see where I have made an error with using the hard-coded "Environments" string when setting environmentsRoothPath.

I will update this.

In regards to 'I believe the provided PoliciesFolder setting should be used to scan for policies. If it's null scan from the root only instead.' this is a separate issue/feature request entirely.

**Comment by ericbeaudry** [comment]
@Norrch2 
It's kind of a blurry line for "another issue" not that I mind opening another one, just that the issue is about 2 closely related folder settings improperly used. It looks like the code is using the environmentFolder to discover policies instead of the PoliciesFolder define in the config file. In fact the PoliciesFolder is defined in the appsettings.json file but never used anywhere. Which is why I suggested to use it.

**Comment by yoelhor** [comment]
Thanks @Norrch2 for taking the time and fix the issue.
