### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by MobileAir** [azure-ad-b2c/vscode-extension#55]
- Issue Type: `Bug`
- Extension Name: `aadb2c`
- Extension Version: `1.3.0`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.55.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by cgat** [comment]
I just tried to build my policy and got

```
Command 'B2C Policy build' resulted in an error (command 'extension.policy.build' not found)
```

Is this related?

**Comment by trittimo** [comment]
> 
> 
> I just tried to build my policy and got
> 
> ```
> Command 'B2C Policy build' resulted in an error (command 'extension.policy.build' not found)
> ```
> 
> Is this related?

Probably not. I've seen this error when I have an invalid XML file (e.g. a floating > or a missing start/end tag). Try validating your XML files to see if that's the issue. Otherwise you probably should open a new issue with some more details.

**Comment by cgat** [comment]
Resolved via a vscode restart. I didn't my post, but you were replying in the process. Thanks
