### ISSUE TITLE
Default environment name in the extension's settings for Upload all policies

### ISSUE THREAD

**Issue by leniel** [azure-ad-b2c/vscode-extension#6]
I could successfully upload just one policy with this new method described [here](https://github.com/azure-ad-b2c/vscode-extension/blob/master/src/help/policy-upload.md).

However at the end of this doc it's mentioned that it's possible to upload all policies at once. For this to happen we need to [set the default environment name](https://github.com/azure-ad-b2c/vscode-extension/blob/master/src/help/policy-upload.md#uploaded-all-policies-for-an-environment):

> The default environment name in the **extension's settings** needs to be configured before using 'Upload all policies' command.

I'm using the extension `v. 1.2.74` right now... I couldn't find the place to set the default environment name.

Can you explain where it is or the extension in Visual Studio code still needs to be updated?

![2019-08-02_12-10-47 Github](https://user-images.githubusercontent.com/764854/62359033-a990db80-b51e-11e9-9477-7f6336ccb944.png)

Thanks.

**Comment by yoelhor** [comment]
Thanks for the feedback, we just committed the changes yesterday. But we need also to publish the new version. We'll do it very soon. I'll keep you posted.

**Comment by nevseev** [comment]
@leniel this has now been released please checkout the marketplace and update the issue once you're happy

**Comment by yoelhor** [comment]
Closing this issue
